GET http://localhost:3000/users?role=ADMIN

###
GET http://localhost:3000/users/44

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": 3,
  "email": "test@example.com",
  "role": "ADMIN"
}

###
PATCH http://localhost:3000/users/6
Content-Type: application/json

{
  "name": "Apacheee",
  "email": "test@example.com",
  "role": "admin"
}

###
DELETE http://localhost:3000/users/6
Content-Type: application/json

###
GET http://localhost:3000/api/employee?role=ADMINW

###
PATCH  http://localhost:3000/employee/2
Content-Type: application/json

{

  "role": "ADMIN"
}

###
DELETE http://localhost:3000/api/employee/2