version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-database
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d myatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  