POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "alex@example.com",
  "password": "1qaz!QAZ",
  "name": "Alex"
}

###
POST http://localhost:3000/auth/signin
Content-Type: application/json
Authorization: 'Bearer'

{
  "username": "alex@example.com",
  "password": "1qaz!QAZ"
}

###
GET http://localhost:3000/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoiYWxleDJAZXhhbXBsZS5jb20iLCJyb2xlIjoxLCJpYXQiOjE3MzM1NzU3NzUsImV4cCI6MTczMzU3NjM3NX0.J8lR29huoIQsoq3BnGq_cJIkyY56RE0lYxkdeo20k0Y

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoiYWxleDJAZXhhbXBsZS5jb20iLCJyb2xlIjoxLCJpYXQiOjE3MzM1Nzc5MTQsImV4cCI6MTczNjE2OTkxNH0.ZKuFG3EAjJ10YrB_Ff966x4toZLmY0vz0a-1m7OsTd4"
}

###
POST http://localhost:3000/admin/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWxleEBleGFtcGxlLmNvbSIsInJvbGVfaWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMzNzkzNjA3LCJleHAiOjE3MzM3OTcyMDd9.vaXKa1h6kv1pFl0rSGpdYdWoGyPmOkpmZHFspfdOpSQ

{
  "name": "user"
}

###
GET http://localhost:3000/user/1

