version: '3.8'

services:
  k6:
    build:
      context: .
      dockerfile: Dockerfile.k6
    network_mode: "host"  # For Linux
    # network_mode: "bridge"  # For Windows/Mac
    volumes:
      - ./tests/k6:/scripts
      