global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['172.17.0.1:3000'] # for Mac host.docker.internal:3000
    metrics_path: '/metrics'