###
GET http://localhost:3000/users

###
GET http://localhost:3000/books

###
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Deep ML",
  "author": "Dilum Darshana",
  "ratings": 6.0
}